.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gainzcoin_qt test_gainzcoin_qt
clean: FORCE
	$(MAKE) -C .. gainzcoin_qt_clean test_gainzcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_gainzcoin_qt_check
gainzcoin-qt gainzcoin-qt.exe: FORCE
	 $(MAKE) -C .. gainzcoin_qt
